#!/usr/bin/env tsx
/**
 * Generate per-API reference markdown from cached OpenAPI specs.
 *
 *   npm run docs
 *
 * Output:
 *   docs/api-reference/README.md             — index of all APIs + tool counts
 *   docs/api-reference/<api>.md              — one file per Talend API
 *
 * The auto-generated files are marked with a header so contributors don't
 * hand-edit them. Human-curated docs live elsewhere under docs/.
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

import { TMC_APIS, type TmcApi } from "../src/apis.js";
import type { JsonSchema, OpenApiSpec, Operation, Parameter } from "../src/openapi-types.js";
import { generateToolsForSpec, type ToolDescriptor } from "../src/tool-generator.js";

const __dirname = dirname(fileURLToPath(import.meta.url));
const SPECS_DIR = join(__dirname, "..", "specs");
const DOCS_DIR = join(__dirname, "..", "docs", "api-reference");

const HEADER = `<!-- AUTO-GENERATED by scripts/gen-docs.ts. Do not edit by hand. -->
<!-- Run \`npm run docs\` to regenerate after refreshing specs. -->
`;

interface ApiSummary {
  api: TmcApi;
  title: string;
  description: string;
  toolCount: number;
  fileName: string;
}

async function main() {
  await mkdir(DOCS_DIR, { recursive: true });
  const summaries: ApiSummary[] = [];

  for (const api of TMC_APIS) {
    const specPath = join(SPECS_DIR, `${api}.json`);
    let raw: string;
    try {
      raw = await readFile(specPath, "utf8");
    } catch {
      console.warn(`Skipping ${api}: spec not found at ${specPath}. Run \`npm run fetch-specs\`.`);
      continue;
    }
    const spec = JSON.parse(raw) as OpenApiSpec;
    const tools = generateToolsForSpec(api, spec);
    const md = renderApiPage(api, spec, tools);
    const fileName = `${api}.md`;
    await writeFile(join(DOCS_DIR, fileName), md, "utf8");
    summaries.push({
      api,
      title: spec.info?.title ?? api,
      description: (spec.info?.description ?? "").split("\n")[0],
      toolCount: tools.length,
      fileName,
    });
    console.log(
      `  ${api.padEnd(32)} ${String(tools.length).padStart(3)} tools  -> docs/api-reference/${fileName}`,
    );
  }

  const index = renderIndex(summaries);
  await writeFile(join(DOCS_DIR, "README.md"), index, "utf8");
  console.log(`\nWrote ${summaries.length} per-API files + docs/api-reference/README.md`);
}

function renderIndex(summaries: ApiSummary[]): string {
  const total = summaries.reduce((n, s) => n + s.toolCount, 0);
  const rows = summaries
    .slice()
    .sort((a, b) => b.toolCount - a.toolCount)
    .map(
      (s) =>
        `| [${s.title}](./${s.fileName}) | \`${s.api}\` | ${s.toolCount} | ${escapeCell(s.description)} |`,
    )
    .join("\n");

  return `${HEADER}
# Talend TMC API Reference

Auto-generated catalog of every MCP tool exposed by this server. Each tool maps
one-to-one to an OpenAPI operation in the upstream Talend Cloud spec.

**${summaries.length} APIs · ${total} tools** (version \`2021-03\` unless overridden).

See [../setup-wizard.md](../setup-wizard.md) to install credentials, and
[../usage-examples.md](../usage-examples.md) for common workflows.

## Index

| API | Slug | Tools | Summary |
| --- | --- | ---: | --- |
${rows}

## How tool names are formed

\`<api_slug>__<operationId>\` where:
- \`api_slug\` has hyphens replaced with underscores (e.g. \`dynamic-engine\` → \`dynamic_engine\`)
- \`operationId\` is taken straight from the OpenAPI spec, sanitized to \`[A-Za-z0-9_]\`
- Names longer than 64 characters are truncated; duplicates get \`_2\`, \`_3\`, … suffixes

See [../architecture.md](../architecture.md) for the full mapping rules.
`;
}

function renderApiPage(api: TmcApi, spec: OpenApiSpec, tools: ToolDescriptor[]): string {
  const groups = groupByTag(spec, tools);
  const tagSections = [...groups.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([tag, ts]) => renderTagSection(spec, tag, ts))
    .join("\n\n");

  return `${HEADER}
# ${spec.info?.title ?? api}

**Slug:** \`${api}\` · **Version:** \`${spec.info?.version ?? "?"}\` · **Tools:** ${tools.length}

${spec.info?.description ?? ""}

[← Back to API index](./README.md)

## Tools by tag

${[...groups.keys()]
  .sort()
  .map((t) => `- [${t}](#${slugify(t)}) (${groups.get(t)!.length})`)
  .join("\n")}

${tagSections}
`;
}

function renderTagSection(spec: OpenApiSpec, tag: string, tools: ToolDescriptor[]): string {
  const sections = tools
    .slice()
    .sort((a, b) => a.name.localeCompare(b.name))
    .map((t) => renderTool(spec, t))
    .join("\n\n");
  return `## ${tag}\n\n${sections}`;
}

function renderTool(spec: OpenApiSpec, tool: ToolDescriptor): string {
  const op = lookupOperation(spec, tool);
  const params: Parameter[] = [
    ...(spec.paths?.[tool.pathTemplate]?.parameters ?? []),
    ...(op?.parameters ?? []),
  ];

  const paramRows = params
    .filter((p) => p && p.in !== "cookie")
    .map((p) => {
      const type = formatSchemaType(p.schema);
      const req = p.required ? "yes" : "no";
      const desc = escapeCell((p.description ?? "").replace(/\s+/g, " ").trim());
      return `| \`${p.name}\` | ${p.in} | \`${type}\` | ${req} | ${desc} |`;
    });

  const bodyContent = op?.requestBody?.content;
  const bodySection = bodyContent ? renderBodySection(bodyContent) : "";

  return `### \`${tool.name}\`

\`\`\`
${tool.method.toUpperCase()} ${tool.pathTemplate}
\`\`\`

${op?.summary ? `${op.summary}\n` : ""}${
    op?.description && op.description !== op.summary ? `\n${op.description}\n` : ""
  }
${
  paramRows.length
    ? `**Parameters**\n\n| Name | In | Type | Required | Description |\n| --- | --- | --- | --- | --- |\n${paramRows.join("\n")}\n`
    : "_No path/query/header parameters._\n"
}${bodySection}`;
}

function renderBodySection(content: Record<string, { schema?: JsonSchema }>): string {
  const [contentType, mediaType] = Object.entries(content)[0];
  const schemaType = formatSchemaType(mediaType?.schema);
  const ref = mediaType?.schema?.$ref;
  const refStr = typeof ref === "string" ? ` Schema: \`${ref.split("/").pop()}\`.` : "";
  return `\n**Request body** (\`${contentType}\`): \`${schemaType}\`.${refStr}\n`;
}

function lookupOperation(spec: OpenApiSpec, tool: ToolDescriptor): Operation | undefined {
  const item = spec.paths?.[tool.pathTemplate];
  if (!item) return undefined;
  return (item as any)[tool.method] as Operation | undefined;
}

function groupByTag(spec: OpenApiSpec, tools: ToolDescriptor[]): Map<string, ToolDescriptor[]> {
  const out = new Map<string, ToolDescriptor[]>();
  for (const t of tools) {
    const op = lookupOperation(spec, t);
    const tag = op?.tags?.[0] ?? "untagged";
    if (!out.has(tag)) out.set(tag, []);
    out.get(tag)!.push(t);
  }
  return out;
}

function formatSchemaType(schema?: JsonSchema): string {
  if (!schema) return "string";
  if (typeof schema.$ref === "string") return schema.$ref.split("/").pop() ?? "object";
  if (schema.type === "array") {
    const item = schema.items ? formatSchemaType(schema.items) : "any";
    return `${item}[]`;
  }
  if (Array.isArray(schema.type)) return schema.type.join(" | ");
  if (schema.enum) return schema.enum.map((v) => JSON.stringify(v)).join(" | ");
  return (schema.type as string) ?? "object";
}

function slugify(s: string): string {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-|-$/g, "");
}

function escapeCell(s: string): string {
  return s.replace(/\|/g, "\\|").replace(/\n/g, " ").slice(0, 200);
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
